meta_product_name: Replikka
meta_title: Replikka – Replikkate your look !
meta_description: Imagine waking up and receiving a notification that propose you every morning 3 looks to replicate according to your dressing ? That's possible with Replikka !
meta_image: cover.png # should exist in `app/assets/images/`
