class Subcategory < ApplicationRecord
  belongs_to :category

  has_many :pieces

  COLORS = ["Apricot", "Beige", "Black", "Blue", "Brown", "Burgundy", "Coral", "Cream", "Dark green", "Gold", "Green", "Grey", "Khaki", "Light blue", "Lilac", "Mint", "Multicolor", "Mustard", "Navy", "Orange", "Pink", "Purple", "Red", "Rose", "Silver", "Turquoise", "White", "Yellow", "Leopard", "Floral"]

  FABRICS = [
    # { name: "Acrylic", temperature_range: 0..15 },
    # { name: "Bamboo", temperature_range: 18..30 },
    # { name: "Canvas", temperature_range: 10..30 },
    { name: "Wool", temperature_range: -10..15 },
    # { name: "Chiffon", temperature_range: 20..35 },
    { name: "Corduroy", temperature_range: 0..20 }, #velour côtelé
    { name: "Cotton", temperature_range: 0..35 },
    { name: "Denim", temperature_range: 10..25 },
    { name: "Down", temperature_range: -20..5 }, #doudoune
    { name: "Elastane", temperature_range: 15..35 }, #legging, sportswear
    { name: "Fur", temperature_range: -10..5 },
    { name: "Felt", temperature_range: -5..15 }, #feutrine, feutre
    { name: "Flannel", temperature_range: -5..15 }, #carreaux
    { name: "Fleece", temperature_range: -10..15 }, #moumoute
    { name: "Lace", temperature_range: 0..35 },
    { name: "Leather", temperature_range: -5..18 },
    { name: "Linen", temperature_range: 20..35 },
    # { name: "Merino", temperature_range: -10..15 },
    # { name: "Mesh", temperature_range: 25..40 }, #résille
    { name: "Mohair", temperature_range: -5..15 },
    # { name: "Neoprene", temperature_range: 10..25 },
    { name: "Nylon", temperature_range: 10..30 },
    # { name: "Patent leather", temperature_range: 0..20 },
    # { name: "Polyester", temperature_range: 0..30 },
    # { name: "Rubber", temperature_range: 0..30 },
    { name: "Satin", temperature_range: 15..30 },
    { name: "Sequin", temperature_range: 15..35 },
    { name: "Silk", temperature_range: 20..35 },
    { name: "Suede", temperature_range: 0..20 },
    { name: "Tulle", temperature_range: 15..35 },
    { name: "Tweed", temperature_range: -5..15 },
    { name: "Velvet", temperature_range: 0..20 }
    # { name: "Viscose", temperature_range: 15..30 },
  ]

  # category_id: Category.find_by(position:).id

  ITEMS = [
    { name: "Shirts", position: 1 },
    { name: "Blouses", position: 1 },
    { name: "T-shirts", position: 1 },
    { name: "Vest tops & tank tops", position: 1 },
    { name: "Tunics", position: 1 },
    { name: "Crop tops", position: 1 },
    { name: "Short-sleeved tops", position: 1 },
    { name: "¾-sleeve tops", position: 1 },
    { name: "Long-sleeved tops", position: 1 },
    { name: "Bodysuits", position: 1 },
    { name: "Off-the-shoulder tops", position: 1 },
    { name: "Turtlenecks", position: 1 },
    { name: "Peplum tops", position: 1 },
    { name: "Halterneck tops", position: 1 },
    { name: "Other tops & t-shirts", position: 1 },
    { name: "Sweaters", position: 2, temperature_range: -20..20 },
    { name: "Sweatshirts", position: 2, temperature_range: -20..20 },
    { name: "Hoodies", position: 2, temperature_range: -20..20 },
    { name: "Kimonos", position: 2, temperature_range: -20..20 },
    { name: "Cardigans", position: 2, temperature_range: -20..20 },
    { name: "Turtleneck sweaters", position: 2, temperature_range: -20..20 },
    { name: "Other sweaters", position: 2, temperature_range: -20..20 },
    { name: "Boleros", position: 11, temperature_range: -20..20 },
    { name: "Waistcoats", position: 11, temperature_range: -20..20 },
    { name: "Blazers", position: 11, temperature_range: -20..20 },
    { name: "Other blazers", position: 11, temperature_range: -20..20 },
    { name: "Capes & ponchos", position: 3, temperature_range: -20..15 },
    { name: "Coats", position: 3, temperature_range: -20..15 },
    { name: "Gilets & body warmers", position: 3, temperature_range: -20..15 },
    { name: "Jackets", position: 3, temperature_range: -20..15 },
    { name: "Other outerwear", position: 3, temperature_range: -20..15 },
    { name: "Cropped trousers", position:	4, temperature_range: 25..40 },
    { name: "Chinos", position:	4, temperature_range: 10..35 },
    { name: "Wide-leg trousers", position:	4 },
    { name: "Skinny trousers", position:	4 },
    { name: "Tailored trousers", position:	4 },
    { name: "Straight-leg trousers", position:	4 },
    { name: "Leather trousers", position:	4 },
    { name: "Leggings", position:	4 },
    { name: "Harem pants", position:	4 },
    { name: "Other trousers", position:	4 },
    { name: "Boyfriend jeans", position: 5 },
    { name: "Cropped jeans", position: 5 },
    { name: "Flared jeans", position: 5 },
    { name: "High waisted jeans", position: 5 },
    { name: "Ripped jeans", position: 5 },
    { name: "Skinny jeans", position: 5 },
    { name: "Straight jeans", position: 5 },
    { name: "Other jeans", position: 5 },
    { name: "Mini skirts", position: 6 },
    { name: "Midi skirts", position: 6 },
    { name: "Maxi skirts", position: 6 },
    { name: "A-line skirts", position: 6 },
    { name: "Bodycon skirts", position: 6 },
    { name: "Skater skirts", position: 6 },
    { name: "Denim skirts", position: 6 },
    { name: "Pleated skirts", position: 6 },
    { name: "High-waisted skirts", position: 6 },
    { name: "Tulip skirts", position: 6 },
    { name: "Pencil skirts", position: 6 },
    { name: "Other skirts", position: 6 },
    { name: "Low-waisted shorts", position:	7 },
    { name: "High-waisted shorts", position:	7 },
    { name: "Knee-length shorts", position:	7 },
    { name: "Denim shorts", position:	7 },
    { name: "Lace shorts", position:	7 },
    { name: "Leather shorts", position:	7 },
    { name: "Cargo shorts", position:	7 },
    { name: "Other shorts", position:	7 },
    { name: "Mini-dresses", position:	8 },
    { name: "Midi-dresses", position:	8 },
    { name: "Long dresses", position:	8 },
    { name: "Special-occasion dresses", position:	8 },
    { name: "Summer dresses", position:	8, temperature_range: 25..40 },
    { name: "Winter dresses", position:	8, temperature_range: 0..15 },
    { name: "Formal & work dresses", position:	8 },
    { name: "Casual dresses", position:	8 },
    { name: "Strapless dresses", position:	8 },
    { name: "Little black dresses", position:	8 },
    { name: "Denim dresses", position:	8 },
    { name: "Other dresses", position:	8 },
    { name: "Jumpsuits", position: 9 },
    { name: "Playsuits", position: 9 },
    { name: "Other jumpsuits & playsuits", position: 9 },
    { name: "Trouser suits", position: 10 },
    { name: "Skirt suits", position: 10 },
    { name: "Other suits", position: 10 }
  ]
end
